- name: Configure Multi Node Research Environment
  hosts: all
  remote_user: root
  gather_facts: True
  roles:
    - role: hunter
      when: hunter_hosts |bool
    - slurm
    - nfs
    - flightenv
    - role: flightweb
      when: "'login' in group_names"
    - role: ipa
      when: "'ipa' in group_names" 
    - user
