# IPA Settings
## If false then do not proceed to setup IPA server or client
ipa_use: true
## The short hostname of the system to setup as the IPA server
ipa_server: "{{ hostvars[groups['ipa'][0]]['ansible_facts']['hostname'] if groups['ipa'][0] is defined else 'infra01' }}"
## The domain to be used by the IPA server
ipa_domain: "cluster.example.com"
## Password for the 'admin' IPA user
secure_admin_password: MySecurePassword
