- name: Create spool directory
  file:
    path: /opt/flight/opt/slurm/var/spool/slurm.state
    state: directory
    owner: nobody
    group: nobody

- name: Turn on SLURM controller daemon
  service: name=flight-slurmctld state=restarted enabled=yes
  tags:
    - update
