- name: Create spool directory
  file:
    path: /opt/flight/opt/slurm/var/spool
    state: directory
    owner: nobody
    group: nobody

- name: Turn on SLURM exec daemon
  service: name=flight-slurmd state=restarted enabled=yes
  when:
    - not ansible_fqdn in remove_node
  tags:
    - update
    - remove
