- name: Perform Generic Configuration
  include_tasks: generic.yml
  when: "'login' in group_names or 'compute' in group_names"

- name: Perform Controller Configuration
  include_tasks: controller.yml
  when: "'login' in group_names"

- name: Perform Daemon Configuration
  include_tasks: daemon.yml
  when: "'compute' in group_names"
