- name: Ensure self resolvable through /etc/hosts
  blockinfile:
    path: /etc/hosts
    marker: "# {mark} OPENFLIGHT IPA HOST ENTRY - DO NOT TOUCH"
    block: |
      {{ ansible_default_ipv4.address |default(ansible_all_ipv4_addresses[0]) }}    {{ ansible_fqdn }} {{ ansible_hostname }}.{{ cluster_name }} {{ ansible_hostname }}

- name: Allow IPA services through firewall
  firewalld:
    zone: public
    service: "{{ item }}"
    state: enabled
    permanent: yes
    immediate: true
  with_items:
    - ldap
    - ldaps
    - kerberos
    - kpasswd

- name: Allow additional IPA ports through firewall
  firewalld:
    zone: public
    port: "{{ item }}"
    state: enabled
    permanent: yes
    immediate: true
  with_items:
    - 53/udp
    - 53/tcp
    - 389/tcp
    - 636/tcp
    - 88/tcp
    - 88/udp
    - 464/tcp
    - 464/udp

- name: Ensure clean environment
  command: "ipa-server-install --uninstall -U"

- name: Install IPA server
  command: "ipa-server-install -a {{ secure_admin_password }} --hostname {{ ansible_fqdn }} --ip-address={{ ansible_default_ipv4.address |default(ansible_all_ipv4_addresses[0]) }} -r {{ ansible_facts['nodename'].split('.')[1:] |join('.') |upper }} -p {{ secure_admin_password }} -n {{ ansible_facts['nodename'].split('.')[1:] |join('.') }} --no-ntp --setup-dns --forwarder={{ ansible_facts['dns']['nameservers'][0] }} --reverse-zone={{ (ansible_default_ipv4.address |default(ansible_all_ipv4_addresses[0]) |split('.'))[0:2] |reverse |join('.') }} --ssh-trust-dns --unattended"

- name: Set HBAC rules
  ipa_hbacrule:
    name: allow_all
    state: disabled
    ipa_pass: "{{ secure_admin_password }}"

- name: Create Generic Cluster Hostgroup
  ipa_hostgroup: 
    name: cluster
    description: "All cluster hosts"
    state: present
    ipa_pass: "{{ secure_admin_password }}"

- name: Add IPA Test User
  ipa_user:
    name: testuser
    state: present
    givenname: Test User
    sshpubkey:
      - "{{ root user ssh pub key alcescluster? }}"
    ipa_pass: "{{ secure_admin_password }}"

- name: Create Generic Cluster User Group
  ipa_group: 
    name: cluster-users
    description: "Generic cluster users" 
    state: present
    ipa_pass: "{{ secure_admin_password }}" 
    user:
      - testuser
    append: true

- name: Configure Generic Cluster Access Rule
  ipa_hbacrule:
    name: cluster-access
    description: "Allow user access to cluster hosts"
    state: present
    hostgroup:
      - cluster
    usergroup:
      - cluster-users
    service:
      - sshd 
    ipa_pass: "{{ secure_admin_password }}" 
