- name: Create export directories
  file:
    path: "{{ item.value.export }}"
    state: directory
    mode: 0775
  with_dict: "{{ nfs_shares }}"

- name: Create export file
  blockinfile:
    path: /etc/exports
    marker: "# {mark} FLIGHT EXPORT ENTRIES - DO NOT TOUCH"
    block: |
      {% for item in nfs_shares|dict2items %}
      {{ item.value.export }} {{ item.value.export_opts }}
      {% endfor %}
    state: present

- name: Create fstab file
  blockinfile:
    path: /etc/fstab
    marker: "# {mark} FLIGHT NFS ENTRIES - DO NOT TOUCH"
    block: |
      {% for item in nfs_shares|dict2items %}
      {% if item.value.export != item.value.mountpoint %}{{ item.value.export }}    {{ item.value.mountpoint }}    none    defaults,bind    0 0{% endif %}
      {% endfor %}
    state: present

- name: Start NFS server service
  service: "name=nfs-server state=started enabled=yes"

- name: Export mounts
  command: exportfs -va
