- name: Identify hunter nodes
  command: "sudo -i /opt/flight/bin/flight hunter list --plain"
  register: hunter_list
  delegate_to: localhost
  tags:
    - update

- name: Process hunter nodes
  set_fact:
    hunter_nodes: "{{ hunter_nodes | default([]) +  [ {'label' : item.split('\t').4, 'ip' : item.split('\t').2, 'fqdn': item.split('\t').1, 'groups': item.split('\t').3} ] }}"
  loop: "{{ hunter_list.stdout_lines }}"
  delegate_to: localhost
  tags:
    - update

- name: Add hunter nodes to /etc/hosts
  blockinfile:
    path: /etc/hosts
    marker: "# {mark} FLIGHT HUNTER HOSTS ENTRIES - DO NOT TOUCH"
    block: |
      {% for item in hunter_nodes %}
      {{ item.ip }}    {{ item.fqdn }} {{ item.label }}
      {% endfor %}
  tags:
    - update

- name: Collect hunter mac addresses
  shell: "{% for item in hunter_nodes %} sudo -i /opt/flight/bin/flight hunter show {{ item.label }} |grep '{{ item.ip }}' -B 2  |grep ':mac:' |sed 's/.*:mac: //g' ;{%endfor %}"
  register: hunter_macs
  delegate_to: localhost
  tags:
    - update

- name: Add hunter node mac addresses to firewall
  firewalld:
    zone: trusted
    source: "{{ item }}"
    state: enabled
    permanent: yes
    immediate: yes
  loop: "{{ hunter_macs.stdout_lines }}"
  tags:
    - update

- name: Set hunter label in prompt 
  blockinfile:
    path: /etc/profile.d/01-hunter-prompt.sh
    create: yes
    marker: "# {mark} FLIGHT HUNTER PROMPT"
    block: |
      if [ "$PS1" ]; then
      {% for item in hunter_nodes %}
      {% if item.fqdn == inventory_hostname %}
          PS1="[\u@\h\[\e[1;34m\] [{{ item.label }}]\[\e[0m\] \W]\\$ "
      {% endif %}
      {% endfor %}
      fi
  tags:
    - update

