- name: Client already enrolled in IPA?
  stat:
    path: "/etc/ipa/default.conf"
  register: ipa_conf
  failed_when: not ipa_conf.stat.exists
  ignore_errors: true
  tags:
    - never
    - pre
    - update

- name: Join IPA
  command: "ipa-client-install --no-ntp --mkhomedir --ssh-trust-dns --force-join --realm={{ ipa_domain |upper }} --server='{{ ipa_server }}.{{ ipa_domain }}' -p admin -w {{ secure_admin_password }} --domain {{ ipa_domain }} --unattended --hostname={{ ansible_fqdn }}"
  when:
    - not ipa_conf.stat.exists
  tags:
    - never
    - pre
    - update
