- name: Generate temporary genders file
  blockinfile:
    path: /tmp/genders
    create: yes
    marker: "# {mark} FLIGHT HUNTER GENDERS ENTRIES - DO NOT TOUCH"
    block: |
     {% for item in hunter_nodes %}
     {% if item.groups == "|" %}
     {{ item.label }} all
     {% else %}
     {{ item.label }} {{ item.groups |replace('|', ',') }}
     {% endif %}
     {% endfor %}
  tags:
    - pre
    - never

- name: Compress genders
  command: "sudo -i nodeattr -f /tmp/genders --compress"
  register: genders_compress
  tags:
    - pre
    - never

- name: Save genders to file
  blockinfile:
    path: /opt/flight/etc/genders
    marker: "# {mark} FLIGHT HUNTER GENDERS ENTRIES - DO NOT TOUCH"
    block: |
       {% for line in genders_compress.stdout_lines %}
       {{ line }}
       {% endfor %}
  tags:
    - pre
    - never

- name: Remove temporary genders file
  file:
    state: absent
    path: /tmp/genders
  tags:
    - pre
    - never
