- name: Identify hunter nodes
  command: "sudo -i /opt/flight/bin/flight hunter list --plain"
  register: hunter_list
  delegate_to: localhost
  tags:
    - update

- name: Process hunter nodes
  set_fact:
    hunter_nodes: "{{ hunter_nodes | default([]) + [ item.split('\t') ] }}"
  loop: "{{ hunter_list.stdout_lines }}"
  delegate_to: localhost
  tags:
    - update

- name: Add hunter nodes to /etc/hosts
  blockinfile:
    path: /etc/hosts
    marker: "# {mark} FLIGHT HUNTER HOSTS ENTRIES - DO NOT TOUCH"
    block: |
      {% for item in hunter_nodes %}
      {{ item.2 }}    {{ item.1 }} {{ item.4 }}
      {% endfor %}
  tags:
    - update

- name: Collect hunter mac addresses
  shell: "{% for item in hunter_nodes %} sudo -i /opt/flight/bin/flight hunter show {{ item.4 }} |grep '{{ item.2 }}' -B 2  |grep ':mac:' |sed 's/.*:mac: //g' ;{%endfor %}"
  register: hunter_macs
  delegate_to: localhost
  tags:
    - update

- name: Add hunter node mac addresses to firewall
  firewalld:
    zone: trusted
    source: "{{ item }}"
    state: enabled
    permanent: yes
    immediate: yes
  loop: "{{ hunter_macs.stdout_lines }}"
  tags:
    - update
